// Shared residents data to ensure consistency across all pages
export const RESIDENTS_DATA = [
  { 
    id: 1, 
    name: 'Nguyễn Văn A', 
    englishName: 'Alice Johnson',
    age: 78, 
    room: '101', 
    careLevel: 'Low', 
    admissionDate: '2023-02-15',
    medicalConditions: ['Tăng huyết áp', 'Viêm khớp'],
    medications: ['Lisinopril', 'Ibuprofen'],
    allergies: ['Penicillin'],
    emergencyContact: 'Nguyễn Văn B',
    contactPhone: '(555) 123-4567',
    personalNotes: 'Thích đọc sách và làm vườn. Cần hỗ trợ tắm rửa.',
    dietaryRestrictions: 'Ít muối',
    mobilityStatus: 'Sử dụng khung đi bộ'
  },
  { 
    id: 2, 
    name: 'Trần Thị B', 
    englishName: 'Robert Smith',
    age: 82, 
    room: '102', 
    careLevel: 'Medium', 
    admissionDate: '2023-01-10',
    medicalConditions: ['Tiểu đường', 'Bệnh tim'],
    medications: ['Metformin', 'Atorvastatin'],
    allergies: ['Thuốc Sulfa'],
    emergencyContact: 'Trần Văn C',
    contactPhone: '(555) 234-5678',
    personalNotes: 'Cựu giáo viên. Thích chơi cờ và nghe nhạc cổ điển.',
    dietaryRestrictions: 'Chế độ ăn tiểu đường',
    mobilityStatus: 'Độc lập'
  },
  { 
    id: 3, 
    name: 'Lê Văn C', 
    englishName: 'Mary Williams',
    age: 85, 
    room: '103', 
    careLevel: 'High', 
    admissionDate: '2022-11-23',
    medicalConditions: ['Alzheimer', 'Loãng xương'],
    medications: ['Donepezil', 'Thuốc bổ sung Canxi'],
    allergies: ['Cao su tự nhiên'],
    emergencyContact: 'Lê Thị D',
    contactPhone: '(555) 345-6789',
    personalNotes: 'Cần được định hướng thường xuyên. Thích liệu pháp âm nhạc.',
    dietaryRestrictions: 'Thức ăn mềm',
    mobilityStatus: 'Xe lăn'
  },
  { 
    id: 4, 
    name: 'Hoàng Văn D', 
    englishName: 'James Brown',
    age: 76, 
    room: '104', 
    careLevel: 'Medium', 
    admissionDate: '2023-03-05',
    medicalConditions: ['COPD', 'Viêm khớp'],
    medications: ['Albuterol', 'Acetaminophen'],
    allergies: ['Aspirin'],
    emergencyContact: 'Hoàng Thị E',
    contactPhone: '(555) 456-7890',
    personalNotes: 'Cựu thợ mộc. Thích làm đồ gỗ khi có thể.',
    dietaryRestrictions: 'Không có',
    mobilityStatus: 'Sử dụng gậy'
  },
  { 
    id: 5, 
    name: 'Phạm Thị E', 
    englishName: 'Patricia Davis',
    age: 81, 
    room: '105', 
    careLevel: 'Low', 
    admissionDate: '2023-04-12',
    medicalConditions: ['Tăng huyết áp', 'Trầm cảm'],
    medications: ['Amlodipine', 'Sertraline'],
    allergies: ['Không có'],
    emergencyContact: 'Phạm Văn F',
    contactPhone: '(555) 567-8901',
    personalNotes: 'Cựu giáo viên. Thích làm thủ công và giao lưu.',
    dietaryRestrictions: 'Ăn chay',
    mobilityStatus: 'Độc lập'
  },
]; 